# 数据集路径

datasets:
 - name: "medqa"
   download_file: "medqa/phrases_no_exclude_test.jsonl"
 - name: "pubmedqa"
   download_file: "pubmedqa/ori_pqal.json"
 - name: "mmlu-anatomy"
   download_file: "mmlu/anatomy_test.csv"
 - name: "mmlu-clinical_knowledge"
   download_file: "mmlu/clinical_knowledge_test.csv"
 - name: "mmlu-college_biology"
   download_file: "mmlu/college_biology_test.csv"
 - name: "mmlu-college_medicine"
   download_file: "mmlu/college_medicine_test.csv"
 - name: "mmlu-medical_genetics"
   download_file: "mmlu/medical_genetics_test.csv"
 - name: "mmlu-professional_medicine"
   download_file: "mmlu/professional_medicine_test.csv"
 - name: "jmed"
   download_file: "jmed/20250122_sample_multiple_choice_1094_qwenscored_adjusted.xlsx"
 - name: "care_qa"
   download_file: "care_qa/care_qa.jsonl"
 - name: "medbullets_op4"
   download_file: "medbullets/medbullets_op4.json"
 - name: "medbullets_op5"
   download_file: "medbullets/medbullets_op5.json"
 - name: "medqa_train_small"
   download_file: "medqa/medqa_train_small.jsonl"
 - name: "mmlu-pro_biology"
   download_file: "mmlu-pro/mmlu-pro_biology.jsonl"
 - name: "mmlu-pro_health"
   download_file: "mmlu-pro/mmlu-pro_health.jsonl"

path_download_dir: "../datas/download_files"
path_origin_dir: "../datas/origin_files/origin_files"
path_origin_w_data_label_dir: "../datas/origin_files/origin_files_w_data_label"
path_question_dir: "../datas/question_files/origin_content"
path_evaluation_dir: "../datas/evaluation"